export const REGION_REQUEST = "REGION_REQUEST";
export const REGION_SUCCESS = "REGION_SUCCESS";
export const REGION_FAIL = "REGION_FAIL";

export const COUNTRY_REQUEST = "COUNTRY_REQUEST";
export const COUNTRY_SUCCESS = "COUNTRY_SUCCESS";
export const COUNTRY_FAIL = "COUNTRY_FAIL";